services:
  - type: web
    name: secure-notes-manager
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && cd frontend && npm install && npm run build && cd .. && cp -r frontend/build/* public/
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://secure-notes-manager.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync 